export const GET_ACHIEVEMENTS = 'GET_ACHIEVEMENTS'
export const ADD_ACHIEVEMENT = 'ADD_ACHIEVEMENT'
export const DELETE_ACHIEVEMENT = 'DELETE_ACHIEVEMENT'
export const ACHIEVEMENTS_LOADING = 'ACHIEVEMENTS_LOADING'